<section class="section-layout">
    <div class="main-layout">
        <div class="lg:mx-[83px] xl:mx-[127px] px-[15px]">
            <div class="font-semibold pb-[40px]">
                <a href="/" class="text-redColor text-xs md:text-sm xl:text-base">Home</a>
                <span class="text-slate-400 text-xs md:text-sm xl:text-base">> Sejarah Dinas Pemadam Kebakaran dan Penyelamatan</span>
            </div>
            <div class="flex flex-wrap gap-8">
                <div class="w-full md:w-3/12">
                    <div class="text-center">
                        <img src="/images/logo-damkar.png" alt="logo-disdamkar" class="mb-2 mx-auto w-[40%] md:w-full">
                        <span class="font-semibold text-slate-500 text-xs md:text-sm xl:text-base">Logo Dinas Pemadam Kebakaran dan Penyelamatan Kota Tanjungpinang</span>
                    </div>
                </div>
                <div class="w-full md:w-8/12">
                    <div class="title-main">
                        <h3 class="font-bebasNeue text-[23px] md:text-[27px] lg:text-3xl xl:text-4xl">Sejarah Dinas Pemadam Kebakaran dan Penyelamatan</h3>
                        <span class="text-[#a5a3a3] text-xs md:text-sm xl:text-base">test</span>
                    </div>
                    <div class="text-justify text-sm lg:text-base text-blackColor">
                        <article>
                            <p class="mb-4">Kota Tanjungpinang dibentuk Berdasarkan Undang-Undang Nomor 5 Tahun 2001 Tentang Pembentukan Kota Tanjungpinang, Undang undang ini ditandatangani oleh Presiden RI Abdurrahman Wahid pada tanggal 21 Juni 2001, dan dicatat dalam Lembaran Negara Republik Indonesia Tahun 2001 Nomor 85. Peresmian Kota Tanjungpinang oleh Menteri Dalam Negeri Dan Otonomi Daerah Hari Sabarno, dilaksanakan secara serentak bersama 11 kota lainnya pada tanggal 17 Oktober 2001 di Jakarta.</p>
                            <p class="mb-4">Kota Tanjungpinang terdiri dari 4 kecamatan dan 18 kelurahan, dimana kelurahan dengan luas paling besar adalah Kelurahan Dompak dengan luas wilayah mencapai 30,50 KM<sup>2</sup> sedangkan kelurahan dengan luas paling kecil adalah Kelurahan Penyengat dengan luas 4 KM<sup>2</sup>.</p>
                            <p class="mb-4">Sementara itu, kecamatan yang memiliki wilayah paling luas terdapat di kecamatan Tanjungpinang Timur dengan luas wilayah mencapai 83,50 KM<sup>2</sup> dan kecamatan dengan luas paling kecil terdapat di kecamatan Tanjungpinang Barat dengan luas 34,50 KM<sup>2</sup>.</p>
                            <p class="mb-4">Jumlah penduduk dapat dikatakan sebagai aset penting dalam menggerakkan roda pembangunan suatu daerah. Dari tahun ke tahun, jumlah penduduk kota Tanjungpinang mengalami laju pertambahan yang berarti. Menurut data Disdukcapil Kota Tanjungpinang, pada tahun 2014 jumlah penduduk Kota Tanjungpinang tercatat sebesar 243.686 jiwa dengan tingkat pertumbuhan mencapai 4,39% dari kepadatan penduduk setiap kecamatan terlihat bahwa penduduk terpadat berada di Kecamatan Tanjungpinang Barat, dengan jumlah penduduk sebanyak 61.493 jiwa dan luas wilayah 34,5 km<sup>2</sup>. Hal ini dapat diartikan bahwa di setiap km<sup>2</sup> wilayah Kecamatan Tanjungpinang Barat terdapat penduduk sebanyak 1.782 jiwa. Selanjutnya diikuti oleh Kecamatan Tanjungpinang Timur dengan 975 jiwa/km<sup>2</sup> dan Kecamatan Bukit Bestari serta Kecamatan Tanjungpinang Kota masing‐masing dengan 925 jiwa/km<sup>2</sup> dan 450 jiwa/km<sup>2</sup></p>
                            <p class="mb-4">Dari Data Tersebut semakin menunjukkan peningkatan perkembangan yang pesat. Seiring dengan jumlah penduduk dan pemukiman Padat Penduduk yang bertambah, ini berpengaruh pada Tata ruang Wilayah yang tidak tertata dapat menyebabkan lingkungan Rawan kebakaran dan bencana lainnya. Hal ini dapat mempengaruhi Kualitas Pelayanan Kepada Masyarakat dalam hal bidang kebakaran dan bencana lainya. Untuk mendukung Kinerja Pemerintah Daerah dalam melaksanakan Urusan Pemerintahan Bidang Pemadam kebakaran dan penyelamatan, maka pada tahun 2014 terbit Undang – Undang Nomor 23 Tahun 2014 sebagai perubahan atas Undang – Undang Nomor 32 Tahun 2004 tentang Pemerintahan Daerah. Di dalam Undang – Undang ini urusan kebakaran masuk ke dalam rumpun urusan wajib yang berkaitan dengan pelayanan dasar. Pada Pasal 12 berbunyi bahwa Pemadam Kebakaran masuk menjadi rumpun urusan wajib yang berkaitan dengan pelayanan dasar. Setelah itu muncul Peraturan Menteri Dalam Negeri Nomor 114 Tahun 2018 Tentang Standar Teknis Pelayanan Dasar, Pada Standar Pelayanan Minimal Sub Urusan Kebakaran Daerah Kabupaten/Kota. Selanjutnya keluar lagi Peraturan Menteri Dalam Negeri Nomor 13 Tahun 2019 Tentang Pakaian Dinas Bagi Aparatur Sipil Negara Di Lingkungan Perangkat Daerah Yang Menyelenggarakan Sub Urusan Kebakaran.</p>
                            <p class="mb-4">Khusus di Kota Tanjungpinang bahwa Pemadam Kebakaran dulunya pernah bergabung di Satuan Polisi Pamong Praja Kota Tanjungpinang sejak tahun 2001. Pada tahun 2003 lahirlah Peraturan Daerah Kota Tanjungpinang Nomor 06 Tahun 2003 Tentang Pembentukan Organisasi Dan Tata Kerja Satuan Polisi Pamong Praja Kota Tanjungpinang Pasal 7 ayat (1) huruf e dimana posisi Pemadam Kebakaran pada waktu itu masih berupa Seksi. Setelah terbentuknya Badan Penanggulangan Bencana Daerah Kota Tanjungpinang yang dituangkan dalam Peraturan Daerah Kota Tanjungpinang Nomor 03 Tahun 2012 Tentang Organisasi Dan Tata Kerja Badan Penanggulangan Bencana Daerah Kota Tanjungpinang dan Peraturan Daerah Nomor 06 Tahun 2014 Tentang Perubahan Atas Peraturan Daerah Nomor 03 Tahun 2012 Tentang Organisasi Dan Tata Kerja Badan Penanggulangan Bencana Daerah Kota Tanjungpinang maka Pemadam Kebakaran Kota Tanjungpinang menjadi bagian dari Badan Penanggulangan Bencana Daerah.</p>
                            <p class="mb-4">Dalam perubahan Peraturan Daerah ini dimasukkanlah seksi Pemadam Kebakaran didalamnya, Selanjutnya pada tahun 2016 muncul lagi Peraturan Daerah Nomor 11 Tahun 2016 Tentang Pembentukan Dan Susunan Perangkat Daerah Kota Tanjungpinang dimana Satuan Polisi Pamong Praja berubah nomenklatur menjadi Satuan Polisi Pamong Praja dan Penanggulangan Kebakaran Kota Tanjungpinang. Berdasarkan Peraturan Daerah tersebut maka posisi Pemadam Kebakaran yang tadinya berada di Badan Penanggulangan Bencana Daerah kembali ke Satuan Polisi Pamong Praja. Berbeda dengan sebelumnya yang hanya berupa seksi. Pemadam Kebakaran kali ini memiliki satu bidang dan dua seksi yaitu Seksi Pencegahan dan Pemberdayaan Masyarakat dan Seksi Operasi Kebakaran. Selanjutnya Tahun 2020 Berdasarkan Peraturan Daerah Kota Tanjungpinang Nomor 6 Tahun 2020 tentang Perubahan Atas Peraturan Daerah Kota Tanjungpinang Nomor 11 Tahun 2016 Tentang Pembentukan dan Susunan Perangkat Daerah Kota Tanjungpinang. Pasal 4 ayat 1 Huruf d angka 19 maka terbentuklah Dinas Pemadam Kebakaran dan Penyelamatan Kota Tanjungpinang, yang diperkuat dengan Peraturan Walikota Tanjungpinang Nomor 10 Tahun 2021 tentang Susunan Organisasi.</p>
                            <p class="mb-4">Kedudukan, Tugas dan Fungsi Serta Tata Kerja Dinas Pemadam Kebakaran dan Penyelamatan Kota Tanjungpinang. Tugas pokok dan fungsi Dinas Pemadam Kebakaran dan Penyelamatan Kota Tanjungpinang berdasarkan Peraturan Walikota Tanjungpinang Nomor 10 Tahun 2021, Membantu Walikota Dalam melaksanakan Urusan Pemerintahan Bidang Pemadam kebakaran dan Penyelamatan yang berkedudukan di bawah dan bertanggung jawab pada Walikota.</p>
                        </article>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>